name: Electronegativity
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - uses: doyensec/electronegativity-action@v1.1
        with:
          input: src/
          electron-version: "15.5.7"
          severity: medium

      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ../results
